name: CI

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - VERSION
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - VERSION
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grab the version to use.
        id: vars
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Build the Docker Image.
        run: docker build --progress plain --tag elasticsearch-curator:${{ steps.vars.outputs.version }}-ci$(date +%s) .
